### ISSUE TITLE
Add Organization Secret SUB_MODULE_PAT to dependabot 

### ISSUE THREAD

**Issue by medgar-nitric** [nitrictech/java-sdk#47]
Add Organization Secret `SUB_MODULE_PAT` to dependabot so it can raise dependency PRs. Please see guide below:

https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/managing-encrypted-secrets-for-dependabot

Currently the run tests workflow fails:

```
run_tests
Input required and not supplied: token
```

Workflow file:

```
name: tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          token: ${{secrets.SUB_MODULE_PAT}}
          submodules: recursive
```

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1e4e0kp) by [Unito](https://www.unito.io)
